### ISSUE TITLE
HTTP POST for search(select)

### ISSUE THREAD

**Issue by csabapalfi** [lbdremy/solr-node-client#110]
Would you be interested in adding POST support for search(select) as well? 

This is to allow really long queries as Tomcat/Jetty limits URL length* by default**.

I'm happy to contribute some code as well. By the look of it it's a bad idea to extend Client.get as it always does GETs. Maybe a new method?

I also understand if you want to keep the module clean and not include something like this even though Solr supports it.

*actually it limits max header length which includes the URL

**Tomcat/Jetty config can be changed but still

**Comment by csabapalfi** [comment]
Closing this now as https://github.com/lbdremy/solr-node-client/pull/121 does this.

**Comment by cbollerud** [comment]
Is anything else needed for this pull request?

**Comment by csabapalfi** [comment]
Not sure. I'm not a repo owner. I guess you can just ask @lbdremy in a comment on that PR.
