### ISSUE TITLE
Sort does not work

### ISSUE THREAD

**Issue by madept** [lbdremy/solr-node-client#115]
I am simply using a sort in following way 

 var query = getMeasurement.createQuery()
                       .q({customerId:id+' AND type:measurements'})
                       .sort("creationDate desc")
                       .start(pageNumber*pageSize)
                       .rows(pageSize);

and on solr it is sending blank sort

[qtp621744031-12] INFO  org.apache.solr.core.SolrCore  – [collection1] webapp=/solr path=/select params={sort=&start=5&q=customerId:BF64629FF41E46443699FB8BE33788C1+AND+type:measurements&wt=json&rows=5} hits=15 status=0 QTime=3

Is that a library issue or i am missing something ?

Regards,
Krish

**Comment by ChannyAzar** [comment]
How can I sort by geodist?
Following is not working:
`.sort({'geodist()' : 'asc' })`

**Comment by luketaverne** [comment]
Hi,

I don't have access to my computer for another day or two, but maybe this
will help you in the meantime.

According to this [page](
https://cwiki.apache.org/confluence/display/solr/Spatial+Search), you can
do something like "&q=*:*&fq={!geofilt sfield=store}&pt=45.15,-93.85&d=5"

If you can't get the fq part using our function, you can manually add
components to the URL using another function (I forget which. You can look
in lib/query.js).

Again, I'll look into this a bit more when I have my computer again.

**Comment by ChannyAzar** [comment]
Thanks. We succeeded in another way.

**Comment by luketaverne** [comment]
Would you mind posting an example here? It might help someone else in the
future, and we can also consider adding new features to the package.

**Comment by ChannyAzar** [comment]
Yes, sure.
```javascript
var solrQuery = client.createQuery()
.q(query)
.set("spatial=true")
.set("pt=" + request['LATITUDE'] + "," + request['LONGITUDE'])
.set("sfield=mySfield")
.set("d=" + request['RADIOUS'])
.set("fq={!geofilt}")
.fl(escape("*,score,_dist_:geodist()"))
.sort({"geodist()": "asc"})
```
Will be very useful to have the `fq`, `pt`, `d` and `sfield` API functions.
I think `pt` it's a very basic function that not already present, we had to switch to custom code.
Also, took to us long time to find this alternative, there is not enough documentation for the `set` function.
We switched from another library, there we can easily use those functions:
```javascript
option.pt = request['LATITUDE'] + "," + request['LONGITUDE'];
option.d = request['RADIOUS'];
option.fl = "*,score,_dist_:geodist()";
option.sfield = 'mySfield';
option.sort = 'geodist() asc';
option.fq = '{!geofilt}';
```
