### ISSUE TITLE
Is `autoCommit` no longer an option?

### ISSUE THREAD

**Issue by julianlam** [lbdremy/solr-node-client#127]
I was passing in `autoCommit` as an option to the `Client` object, but since upgrading to v0.5.0 from v0.2.9, I can't find any reference to "autoCommit" anywhere in the code except for the `/tests` folder.

Seems like a breaking change to me, and so its removal should have been logged in the migration steps :smile:

**Comment by ColadaFF** [comment]
autoCommit now only works as a functions, because multiple docs could be submitted but not committed at the same time.

-- Sure it needs to be.
In the next weeks the docs will be updated.

**Comment by manigk** [comment]
I have same problem Client.autoCommit() not working, i'm using solr-cloud 5.5.2 and node v5.0.0.
please give solution.
