### ISSUE TITLE
Query highlighting - 'hl' parameter support

### ISSUE THREAD

**Issue by woodenfish** [lbdremy/solr-node-client#130]
Do you plan to support the 'hl' query param? If you do,then when?

**Comment by ColadaFF** [comment]
No, there is no plans for the hl query param, but of course you could submit a pull request. :D

**Comment by luketaverne** [comment]
Added support here for all query highlighting parameters listen in the Solr v5.0 docs. Will test it tomorrow morning/ afternoon, then pull it in if no-one objects.

3847c9de326d99cec15e967135150f092b1a0d6c
