### ISSUE TITLE
Node.JS 0.12 Request error

### ISSUE THREAD

**Issue by NickNaso** [lbdremy/solr-node-client#131]
Hi,
when i use solr-node-client with node 0.12  i receive this error in response:
```javascript
{ [Error: connect ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'connect' }
}
```
My call i as reported below:
```javascript
var Solr = require('solr-client');

var solrClient = Solr.createClient({
    host: "127.0.0.1",
    port: "8983",
    core: "corename",
    path: "/solr",
    agent: "",
    secure: false
});
solrClient.basicAuth("username", "password");

var query = solrClient.createQuery().q("prova");

solrClient.search(query, function(err, obj){
    if(err){
        console.info(err);
    } else {
        console.info(obj);
    }
});
```
The same code works perfectly with node 0.10.38. 
Is there some issue with request?
Thanks in advance.

**Comment by ColadaFF** [comment]
Hi there,
Can you create a jsbin or something to reproduce the error ? 
I just test you code and works fine.

**Comment by nicolasembleton** [comment]
From what I can see your instance isn't available. If you access it from your browser with "http://localhost:8983/solr" do you have something? Are you using on windows or *nix?

**Comment by nicolasembleton** [comment]
@NickNaso Are you still facing the issue? Were anyone able to reproduce it? It looks like an environment problem to me. I'd like to close this issue if no one objects (@Nick mainly).

**Comment by NickNaso** [comment]
Ok close this issue. Sorry form my delay but i was busy in this period. Yes it's an environment problem when i reinstalled and setted all on other machine all seems work fine. Thanks everyone.

**Comment by nicolasembleton** [comment]
No problem. Thanks for the feedback.
