### ISSUE TITLE
Updating documents in solr

### ISSUE THREAD

**Issue by KlwntSingh** [lbdremy/solr-node-client#134]
Hello,

I wanted to update the documents in solr and i have seen the update code in lib.js of solr-node-client so i just wanted example showing how to update the document.
Please Help!

Thanks

**Comment by ColadaFF** [comment]
That's easy.
You have to options, one is doing it by solr method.
The solr method is the same like indexing, the thing here is you need the id of the document you want to update, i.e: in your core you have a field name id that you set like: 
```xml
 <field name="id" type="string" multiValued="false" indexed="true" required="true" stored="true"/>
<!-- And then... -->
<uniqueKey>id</uniqueKey>
```
So, with solr-client, your update will look like: 
```javascript
solrClient.add({
  "id": documentId,
  "field1": field1,
  "field2": field2
}, function(response) {
  console.log(response);
}, function(err) {
  console.error(err);
});
```
Solr will lookup for an Id and update the whole document if it finds it.
The other way you have is using the update provided by solr-client, in this case, the method: 
```javascript
solrClient.update();
```
Refers to an update command to solr, so you can do whatever solr has available in this command, like delete, add, commit, optimize...
In this case you need to send a JSON object with the command to execute by solr, i.e:
```javascript
"add": {
  "commitWithin": 5000,          /* commit this document within 5 seconds */
  "overwrite": false,            /* don't check for existing documents with the same uniqueKey */
  "boost": 3.45,                 /* a document boost */
  "doc": {
    "f1": "v1",
    "f1": "v2"
  }
}
```
-- JSON Object example by solr Docs.

You can view a full documentation here: https://wiki.apache.org/solr/UpdateJSON
