### ISSUE TITLE
createClient() param options

### ISSUE THREAD

**Issue by dschinkel** [lbdremy/solr-node-client#139]
Where are these params documented?   for example:

createClient('someServer', port, '', ...);

**Comment by dschinkel** [comment]
I found it in your source code but can you please document it and make it obvious in the site docs.

**Comment by lbdremy** [comment]
The documentation is available here http://lbdremy.github.io/solr-node-client/code/solr.js.html. The code is well documented with JSDoc so it is easy to get this kind of information.

**Comment by dschinkel** [comment]
weird for some reason I didn't see that, thanks.
