### ISSUE TITLE
UPDATE_HANDLER & UPDATE_JSON_HANDLER

### ISSUE THREAD

**Issue by fractalf** [lbdremy/solr-node-client#142]
The default handlers are defined in lib/solr.js in line 88.

The UPDATE_JSON_HANDLER doesn't work for our v4 solr server, so I made a quick fix:
https://github.com/fractalf/solr-node-client/commit/b9a38d64543a28386a4ea95182086d55c2c783be

However this is not compatible with v3.1, so a proper fix sould be applied. Or at least allow this to be passed as an option.

From the solr docs:
"In Solr4.0, JSON support is included in the standard UpdateRequestHandler"
https://wiki.apache.org/solr/UpdateJSON

**Comment by luketaverne** [comment]
Good catch. It looks like this is also the case for Solr5.0. I'm currently downloading Solr3.1 so I can write and test something that works for both versions.

**Comment by luketaverne** [comment]
@fractalf and @lbdremy, let me know if this looks good to you: 870ca7daa5a818a29fdeda464f0679813238efdb

I thought of adding a version number to the client constructor, but it seems a bit overkill to add it to the constructor. With this method, we can continue to provide (a reasonable amount of) backwards compatibility as Solr continues to change. Let me know what you think.

**Comment by fractalf** [comment]
Works for me.

5 cents though:
It feels a bit overkill-ish. Maybe just passing an option and setting the value is good enough. I dunno, you decide ;)
````
// This works too
var options = {
    solrVersion: 4
}

this.UPDATE_JSON_HANDLER = options.solrVersion > 3 ? 'update' : 'update/json';
````

**Comment by luketaverne** [comment]
Apologies for all of the commit messages. Having some issues with sending pull requests from the correct branch :)

@fractalf I took your advice on the implementation. Your idea was better.

**Comment by fractalf** [comment]
*thumbs-up* :)
