### ISSUE TITLE
Not working for string with multiple words

### ISSUE THREAD

**Issue by dbanka** [lbdremy/solr-node-client#145]
Using  solr node client when I searched using query ' cateogory:Trade' , the search worked.But when I searched for 'category:Trade Flow' , its returning 400 Bad request.But I checked the query directly in solr,it works there, so what is the problem here?

**Comment by luketaverne** [comment]
I tried this in my own Solr 5.0 installation (with fields that are defined in my schema), and the multiple word strings return a success response.

Can you post the code in question and the version of Solr you are using?

**Comment by dbanka** [comment]
Its solved now. I encoded the string before sending ,now its working

**Comment by luketaverne** [comment]
I was able to submit the query without encoding the string first. The solr-client does its own encoding, in most cases, before submitting the query to Solr. Whitespaces are definitely supposed to be encoded by the library.

**Comment by dbanka** [comment]
client.search('q=category_name:*' + query , function (err, obj) { })
This was the code, when I sent query without encoding, it didn't work

**Comment by luketaverne** [comment]
Ah okay, so this is the problem. The recommended method for constructing queries is:

```var query = client.createQuery(); //create a new query object
query.q({category_name: 'Trade flow'}); //provide object describing the search. You can also provide a string like 'category_name:Trade flow' instead of an object.

client.search(query, function(err,obj){
   ...
});```

You can chain methods together like this,

```query.q('category_name:trade flow').fl('category_name')```

and on and on.

**Comment by dbanka** [comment]
but I didn't find a way to add facet.pivot, thats why I was using the old way

**Comment by nicolasembleton** [comment]
You can just use it like category:"Trade Flow" to make it work. Or
category:("Trade Flow" OR "Something Else"). Wouldn't that work?

**Comment by dbanka** [comment]
Now the issue is closed, I am able to search with multiple words..My only problem now is that I am unable to add "facet.pivot" query with the new format .
I tried something like  : query.facet({'pivot':'category_id'}) . It didn't work and I didn't find anything on it in the documentation.

**Comment by nicolasembleton** [comment]
Hehe. Right. For some reason I jumped one communication. 
Actually you're right. Facet.pivot isn't supported. I'll open a new ticket for that.
