### ISSUE TITLE
Facet.pivot isn't supported

### ISSUE THREAD

**Issue by nicolasembleton** [lbdremy/solr-node-client#146]
Following the discussion thread here https://github.com/lbdremy/solr-node-client/issues/145, we realized that this part from Solr Documentation isn't supported:

```
Facet.pivot

A list of fields to pivot. Multiple values will create multiple sections in the response
&facet.pivot=cat,popularity,inStock&facet.pivot=popularity,cat

facet.pivot.mincount

The minimum number of documents that need to match for the result to show up in the results. 
Default value is 1
```

**Comment by nicolasembleton** [comment]
Pushed in v0.6.0.

**Comment by vaishalibhatkar** [comment]
I have downloaded the  solr 0.6.0 & trying to use solr pivot.
here is  my sample query 
 var query = client.createQuery()
            .q({ 'feed_type':'UNCATEGORIZEDITEM' })
            .start(0)
            .rows(10)
            .facet({pivot:'batch_id,item_status'});
in the response i am not getting getting facet_pivot object. 
facet_counts: 
   { facet_queries: {},
     facet_fields: {},
     facet_dates: {},
     facet_ranges: {},
     facet_intervals: {} } }

please help.
