### ISSUE TITLE
0.6 Release

### ISSUE THREAD

**Issue by nicolasembleton** [lbdremy/solr-node-client#148]
Hi everyone. Preparing 0.6 release. 

Is there anything special or anything that should be included into this new release? 

@lbdremy @ColadaFF @kfitzgerald @luketaverne please chime in for those.

**Comment by luketaverne** [comment]
We can include the admin collections as a "beta"/ "dev" feature.

I should write the tests for the query-highlighting features before the release too. Perhaps I'll work on that tonight. (Currently having trouble getting Solr to run properly on my Macbook, IRC channel members are stumped).

What's the status of the Docker build system? We'll need that to eventually enable the test on the admin-collections.

**Comment by nicolasembleton** [comment]
Wrt the Docker-build system It's in process, docker system is built and I'm writing the test runner, but I'm having issues to make it platform agnostic. Also had a few personal sidetracks. I'll have it done by October. But we can't have it for 0.6. 

I'll work on those document and commit guideline if you guys don't mind. I'm for following @lbdremy and use Angular's which is pretty clean. Will update the contributing and  updating the doc right now.

@luketaverne I'd like to release this week to push things a bit and start showing back activity to the users. Let me know what you can add by then.

**Comment by luketaverne** [comment]
Cool! That will be a really nice tool for the project to have. Good work.

Sounds good wrt following Angular. I don't really have a preference of commit style at this point, so if you guys are happy with it, I'm happy with it.

I just added and merged this (PR)[https://github.com/lbdremy/solr-node-client/pull/150] to add query highlighting test, following Angular style. Everything passing.

Is there anything else you'd like me to work on in the immediate future? I leave in a few hours for a long weekend, so I won't be able to contribute anything more until Sunday night at the earliest.

**Comment by luketaverne** [comment]
Unsure if I mentioned this elsewhere. Should we update the runtime and dev dependencies before the 0.6 release? The list is [here](https://gemnasium.com/lbdremy/solr-node-client). The items needing updates are:

-JSONStream
-request
-bignumber.js
-chai
-mocha

Mocha and chai should probably be updated together.

**Comment by nicolasembleton** [comment]
Very good idea. Will check up on that too and see if the tests are still properly passing. 

Got it for the other points. Thanks for the feedback. I think we are good to go. :) 
Working on the items mentioned above. ETA somewhere around Sunday or Monday for a final review.

**Comment by nicolasembleton** [comment]
As a heads-up, on my side i'm: 
* Done with updating the package.json and tests accordingly, 
* Done with working Docker setup (used it for testing) - not fully integrating with `npm test` yet, 
* Currently digging into updating files `CONTRIBUTIONS.md` - and the commit guidelines, and `gh-pages` documentation as well as GitHub `readme.md`. 

With regards to the doc, I'll try to bring it up-to-date but it will take a bit to make something very clean, so we should target to update it frequently.

**Comment by nicolasembleton** [comment]
Guys, sorry for the delay. Just started a new work so I had little free time. 

I've merged the PR and pushed a 0.6 release: https://github.com/lbdremy/solr-node-client/releases/tag/v0.6.0

@luketaverne @kfitzgerald @ColadaFF @lbdremy If you guys have time, would you mind checking up the release at that version? It should work fine but I'd like to make sure before releasing.

@lbdremy I can't find any option in NPM UI to update the release, what is the procedure there?

**Comment by nicolasembleton** [comment]
Oh. I think I forgot to update the Package.json version number -_-. Dumb. Will fix that.

**Comment by luketaverne** [comment]
I pulled it over to the project I'm currently developing at work (from github directly). Everything seems to work as it did before the changes. Nice work!

**Comment by nicolasembleton** [comment]
Thanks @luketaverne . @lbdremy Finally found the way to push. :) So NPM was updated to 0.6.0 (`0.6.0 is the latest of 23 releases`)
