### ISSUE TITLE
Is the solr client stateless?

### ISSUE THREAD

**Issue by cressie176** [lbdremy/solr-node-client#169]
Should I cache an instance of the client returned by solr.createClient or create a new client per operation?

**Comment by ColadaFF** [comment]
You can create an instance and use then wherever you want.

For example, in my project I have an instance that waits for the core name and the others params, then I export them and require then in the files that I needed, like:

```javascript
var solr = require('solr-client');
module.exports = function(solr_host, solr_port, coreName){
 return solr.createClient({
            host: solr_host,
            port: solr_port,
            core: coreName,
            path: "/solr"
        });
}
```

Then, in the file that I need to, I require this and instance it, so, it will be an instance per core, and use it as I want to:

```javascript
var solrClientUsers = require('./solrFile.js')('localhost', 8983, 'users');
```

**Comment by cressie176** [comment]
Thanks
