### ISSUE TITLE
Problem with dynamic solr sort query

### ISSUE THREAD

**Issue by bhaveshbhatkar** [lbdremy/solr-node-client#182]
I am using this node.j client & i have a sample query here
 var query = client.createQuery()
            .q(created_dtm:[2016-04-04T20:42:01.482Z TO 2016-04-05T20:42:01.482Z] })
            .start(start)
            .rows(50)
            .sort({created_dtm : desc });
        client.search(query,function(err,data){
if i hard code the sort column name & sort order then it works, 
but my sort column name & sort order is dynamic,  if i store those in a variable & pass those variables
for e.g. 
var a = 'created_dtm';
var b = 'desc';
and then write a query as below 

 var query = client.createQuery()
            .q(created_dtm:[2016-04-04T20:42:01.482Z TO 2016-04-05T20:42:01.482Z] })
            .start(start)
            .rows(50)
            .sort({a : b });

then it does not work. It's very critical to have sorting  working with dynamic values. 
Any help will be appreciated.

**Comment by ColadaFF** [comment]
Hi there,

What I'm seen here is probably a problem with object key assignation, this is what a I mean: 
if you have: 
```javascript
var a = 'created_dtm';
var b = 'desc';
// then if you do this:
var x = { a: b };
/* this is going to make an object like this: {"a": "desc"}
   if you want to make { "created_dtm": "desc" }, you will have to do something like:
*/
var x = {};
x[a] = b;
```

If you can create a variable and do that, there you have your solution, but if don't and want to make it un runtime, you can use [lodash set method](https://lodash.com/docs#set), and your code can be like this: 

```javascript
var a = 'created_dtm';
var b = 'desc';
var query = client.createQuery()
    .q(created_dtm:["2016-04-04T20:42:01.482Z TO 2016-04-05T20:42:01.482Z"] })
    .start(start)
    .rows(50)
    .sort(_.set({}, a, b));
```
