### ISSUE TITLE
Update npm to latest version

### ISSUE THREAD

**Issue by mrlannigan** [lbdremy/solr-node-client#189]
Published version with npm is at 0.6.0 which is based on 41a9b5e.

This commit is before f93e0ee69c543c079d59229b686efe645ff39e93, which contains a fix for the facet pivot addition.

Can we get an updated version to npm?

**Comment by nicolasembleton** [comment]
Yes. Good point. Will do now I have some more time.

**Comment by luketaverne** [comment]
Also going to start working on this package again.

**Comment by mrlannigan** [comment]
@luketaverne this would be amazing. Thanks! If you guys need help let me know.

**Comment by sudowork** [comment]
@nicolasembleton Would also appreciate a new version being published. Was excited for the feature in 0.6.0 to allow POST requests for large requests; however, I noticed that the query params  were being included in both the body and the URI still, causing 414 errors. Seems like 2a57e78 fixes the issue, but hasn't been published yet. Thanks!

**Comment by nicolasembleton** [comment]
Yes this one is very long overdue... Thanks for the reminder. Will try to
push it over the weekend.

**Comment by sudowork** [comment]
Awesome, really appreciate it! Have a great one.

**Comment by smashercosmo** [comment]
@nicolasembleton any luck with cutting new release?)) I'm mostly interested in https://github.com/lbdremy/solr-node-client/pull/172 This is very critical bug fix. Would be glad to provide any help if needed.

**Comment by smashercosmo** [comment]
@nicolasembleton @lbdremy any response on this?

**Comment by nicolasembleton** [comment]
I'll make it done by this weekend! Can't delay that any longer.

**Comment by nicolasembleton** [comment]
@smashercosmo Would you mind making tests pointing your NPM directly to this commit: https://github.com/lbdremy/solr-node-client/commit/dcf31c201a8f1a1c9b26f4ec2c5600156e0b33f5 ? Just to make sure everything works fine.

**Comment by nicolasembleton** [comment]
Release note, let me know guys if I have missed anything:

```
- `*` escaping fl parameter in Query (@Grzegorz Wilk)
- feat(Error): Properly capture and proxy status codes and error messages (@jsvk)
- Do not send the parameters in the url when using POST. (@voidberg)
- Add support for ipv6 when resolving host/hostname (@fractalf)
- URI encode the cursorMark value before use (@flawless2011)
- Only check options.pivot.mincount if options.pivot is available. (@saschagoebel)
- test(rangeFilter): test array of multiple fields and obj of single field (@luketaverne)
```

**Comment by smashercosmo** [comment]
@nicolasembleton awesome, thx. I'll test on wednesday.

**Comment by lebolo** [comment]
@nicolasembleton @luketaverne any chance of publishing the latest code to npm? Particularly interested in the pivot fix.

**Comment by nicolasembleton** [comment]
Hi Luis,

Would you mind testing the latest commit? It's ready to push but need
someone to do double testing before I can push. If it works fine, I'll push
it over the weekend.

Thanks,
Nicolas.

**Comment by sudowork** [comment]
@nicolasembleton, Any luck on getting the next version published?

**Comment by ministrycrm** [comment]
Would be great to get another release to address https://nodesecurity.io/advisories/309 in the latest merge to master.

**Comment by nicolasembleton** [comment]
Excellent point. Very important one... I should have time next week to push
a new version including the latest PRs.
