### ISSUE TITLE
client.search() with much long parameters resulted by POST:: BAD REQUEST

### ISSUE THREAD

**Issue by aulsai** [lbdremy/solr-node-client#193]
I've been using client.search() with so long parameters, 

**Expected result**
then I expected from client.search() that it would be changed to http verb POST with successfully result.

**Observed result**
BAD REQUEST, Because URL is too long.

Note: I've found an issue in **solr-client@0.6.0** **BUT** I have seen in the master that this issue had been fixed by the commit 492937bee165418405ba1bb9720a1c268630281e

So, I did npm install solr-client but I could not get the latest version.

Could you please suggest me, how to get the lastest version via NPM ?

Thanks

**Comment by nicolasembleton** [comment]
Yes. I've just pushed the latest version that fixes that. Please check it out on NPM. I'm closing it for now, if you still have issues, don't hesitate to reopen it.
