### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by cliftonc** [lbdremy/solr-node-client#201]
Is this library maintained?  Would you consider adding other maintainers to get things moving again?

We use it heavily, and really don't want to have to fork it to get PRs etc. merged.

**Comment by nicolasembleton** [comment]
It's a good question. Short answer is `partially`. I have had way less time than necessary to update the library although I'd love to. There is a release pending but been lacking testing. 
However, adding a new maintainer would be absolutely welcome, so if you want to be one of them @cliftonc we should ask @lbdremy . 
Meanwhile, I've committed to push a release this week to deploy all the past PRs and fix a security issue with Request.

**Comment by cliftonc** [comment]
Ok - rest assured I understand the challenges of keeping something like this ticking along, really appreciate all the effort you're putting in.

I'd be happy to dedicate some engineering time from my company to help (not sure it would be me directly).  We have a number of our own projects that we maintain so would be happy to explore ways to contribute back given how much use we make of this.

Happy to jump on a quick call with yourself / @lbdremy - or just chat offline via this issue / email - whatever works for you guys.

**Comment by nicolasembleton** [comment]
Perfect. Appreciate the effort! Would you guys be ready to help testing that things still work correctly right before I push the new release?

**Comment by cliftonc** [comment]
Yes, happy to.

**Comment by nicolasembleton** [comment]
Awesome. Thank you. That should be soon this week. 

With regards to adding you as a committer, only @lbdremy can do that so I'll see if we can have him do it. He seldom stops around as he's moved away for his own thing quite a while ago. But @lbdremy if you read this, please add @cliftonc to the list of committers.

**Comment by cliftonc** [comment]
Great - I have @loveirobert lined up this side to put the new version in our biggest app using it and test: https://www.tes.com/resources/search/.

**Comment by nicolasembleton** [comment]
Massive! Thanks guys. Will keep you posted.

**Comment by loveirobert** [comment]
@nicolasembleton thanks for helping us! I'm waiting for your notification.

**Comment by nicolasembleton** [comment]
Hi guys, going to have a release ready for testing in a few hours. Will keep you posted.

**Comment by loveirobert** [comment]
@nicolasembleton will do the upgrade on our end and test

**Comment by nicolasembleton** [comment]
Thanks. @loveirobert , the newer 0.7.0 package can be found in that branch: https://github.com/lbdremy/solr-node-client/tree/v0.7.0-test 
If the tests are successful I'll merge it to Master and create a reselase

**Comment by loveirobert** [comment]
@nicolasembleton i'll notify you about the results

**Comment by lbdremy** [comment]
Hi guys, I just sent an invite to you @cliftonc and @loveirobert

**Comment by loveirobert** [comment]
@nicolasembleton @cliftonc @lbdremy
All our tests are green with v0.7.0-test and we don't see any performance issues.

**Comment by nicolasembleton** [comment]
Perfect. Thanks guys. Am traveling atm but will push 0.7.0 early next week.
Now you're in you can do it too if you want ;). Either way works for me.

**Comment by aartiles** [comment]
Hi,
Any ETA for the 0.7 release? We have some packages failing to pass the Node Security tests due to this vulnerability on the v0.6.0 https://nodesecurity.io/advisories/309

**Comment by nicolasembleton** [comment]
Let me do it now. Came back yesterday so can do it.

**Comment by nicolasembleton** [comment]
There you go: https://github.com/lbdremy/solr-node-client/releases/tag/v0.7.0

**Comment by aartiles** [comment]
Excellent, thanks guys!
