### ISSUE TITLE
[Question] working with multiple cores

### ISSUE THREAD

**Issue by StlthyLee** [lbdremy/solr-node-client#204]
I've just stumbled across solr-node-client while looking for information on how to perform deletes by ID in Solr.

So far it looks like solr-node-client could actually help with all interactions with Solr in our application where I work. However after reading through the docs it isn't clear to me how you would go about targeting a specific core unless I've missed something. 

Say for instance I had three cores: _Core A_, _Core B_, and _Core C_: and I wanted to delete a document from _Core B_ after the removing said information has been deleted by the user from our application, how would I go about this using solr-node-client?

**Comment by StlthyLee** [comment]
no need to worry about this, I found the answer by accident :)

**Comment by nicolasembleton** [comment]
Post it here so others can find it too ;)

**Comment by StlthyLee** [comment]
The answer is actually here: 
https://github.com/lbdremy/solr-node-client/issues/169
