### ISSUE TITLE
Replace request with undici

### ISSUE THREAD

**Issue by kibertoad** [lbdremy/solr-node-client#252]
We should replace deprecated `request` with `undici`, which is **by far** the fastest HTTP client out there. See benchmarks: https://nodejs.medium.com/introducing-undici-4-1e321243e007

**Comment by rudolfbyker** [comment]
It might be useful to do this simultaneously with https://github.com/lbdremy/solr-node-client/issues/251 because the node http module is where most of our callback entanglement lies.

**Comment by kibertoad** [comment]
@rudolfbyker Makes sense!

**Comment by rudolfbyker** [comment]
Replaced by https://github.com/lbdremy/solr-node-client/issues/286
