### ISSUE TITLE
Using dynamic `require` instead of `import` in tests hides typescript errors.

### ISSUE THREAD

**Issue by rudolfbyker** [lbdremy/solr-node-client#282]
The tests use `require('...')` to import from the library, and it's using a dynamically calculated variable from the environment to determine the path. This is hiding a lot of Typescript errors that currently exist in the tests.

**Comment by kibertoad** [comment]
Good one!

**Comment by rudolfbyker** [comment]
I have a feeling we should replace ALL `require`s with `import`s, and remove `'@typescript-eslint/no-var-requires': 'off',` from the eslint config.

**Comment by kibertoad** [comment]
Yes, we definitely should.
