### ISSUE TITLE
Wrap requests in promises when callback is not set

### ISSUE THREAD

**Issue by kibertoad** [lbdremy/solr-node-client#284]
This is a common pattern for libraries that support both callback-based and promise-based APIs. Current promisify-based approach does not provide proper typings.

**Comment by rudolfbyker** [comment]
Alternative idea: Get rid of callbacks entirely, and write nice async functions. It's easier/cleaner to wrap an async function to make it work with callbacks than the other way around.

**Comment by kibertoad** [comment]
Checked how undici does it, and yeah, it seems to have dropped callbacks as well.
Sure, let's do that then.
Let's combine move to async with move to axios or superagent then (request doesn't support promises and is deprecated anyway)
