### ISSUE TITLE
Temporarily getting EADDRNOTAVAIL after many http.requests

### ISSUE THREAD

**Issue by jochenonline** [lbdremy/solr-node-client#73]
I am adding many documents to Solr (localhost). After round about 32000 documents Solr becomes unavailable from node.js. All `http.request` against Solr return `EADDRNOTAVAIL`. Requests from other clients (i.e. `curl http://localhost/solr/#/mycore`) work without any problems. After 5-10 seconds the requests from node.js work again also. After a while (mostly 15 seconds) the temporarily unavailability appears again. Do you have any idea what makes node.js not beeing able to connect to Solr from time to time and what makes it "self-healing"? Does this have to do something with the number of available sockets?

**Comment by tylercollier** [comment]
Thanks @jochenonline. `agent: false` worked for me.
